name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.11]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Print Python information
        run: python --version

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Verify code format with black
        run: |
          pip install black
          black . --check

      - name: Verify code linting with pylint
        run: |
          pip install pylint
          cd src
          PYTHONPATH=. pylint --disable=R,C battleship
          cd ..

      - name: Run unit tests
        run: |
          pip install pytest
          PYTHONPATH=src pytest

      - name: Build Python packages
        run: |
          pip install twine wheel
          python setup.py sdist bdist_wheel

      - name: Deploy Python packages to PyPI
        run: python -m twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
